// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testconsole;

namespace testconsole.Migrations
{
    [DbContext(typeof(UseInfoDBContext))]
    [Migration("20181101074606_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testconsole.EntityModels.IMContactInfo", b =>
                {
                    b.Property<int>("IMContactInfoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactAccount");

                    b.Property<string>("ProductName");

                    b.Property<string>("ProductProvider");

                    b.Property<int>("UserInfoId");

                    b.HasKey("IMContactInfoId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("IMContactInfo");
                });

            modelBuilder.Entity("testconsole.EntityModels.UserInfo", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPassword");

                    b.HasKey("UserInfoId");

                    b.ToTable("users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserInfo");
                });

            modelBuilder.Entity("testconsole.EntityModels.Student", b =>
                {
                    b.HasBaseType("testconsole.EntityModels.UserInfo");

                    b.Property<int>("Grade");

                    b.Property<int>("GraduateLevel");

                    b.Property<string>("Major");

                    b.ToTable("Student");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("testconsole.EntityModels.IMContactInfo", b =>
                {
                    b.HasOne("testconsole.EntityModels.UserInfo", "UserInfo")
                        .WithMany("UserIMContacts")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
